Grep
e5l/SoftwareDesignAU pull request #2
Opened 2016-09-22 19:44 UTC by e5l

implement grep

2016-09-25 21:17 UTC, yurii-litvinov requested changes
если делать прямо из консоли
grep -i "antlr" build.gradle 
то получается
line 1:5 token recognition error at: '-'
Too many positional arguments provided. Provided 3, expected no more than 2
line 1:5 token recognition error at: '-'

2016-09-26 05:25 UTC, e5l commented
как конкретно запускали?


Леонид Сташевский, 6 курс SE

> On Sep 26, 2016, at 00:17, Yurii Litvinov <notifications@github.com> wrote:
> 
> @yurii-litvinov requested changes on this pull request.
> 
> если делать прямо из консоли
> grep -i "antlr" build.gradle 
> то получается
> line 1:5 token recognition error at: '-'
> Too many positional arguments provided. Provided 3, expected no more than 2
> line 1:5 token recognition error at: '-'
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/e5l/SoftwareDesignAU/pull/2#pullrequestreview-1460911>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AEF18zXEy2S4jPEq82TG4pC2wOdEitxGks5qtuTWgaJpZM4KEST2>.
>

2016-09-26 05:28 UTC, e5l commented
Вот из консоли запуск, то же самое.



> On Sep 26, 2016, at 08:25, Leonid Stashevsky <leonid.stashevsky@gmail.com> wrote:
> 
> как конкретно запускали?
> 
> <PastedGraphic-1.png>
> Леонид Сташевский, 6 курс SE
> 
>> On Sep 26, 2016, at 00:17, Yurii Litvinov <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> @yurii-litvinov requested changes on this pull request.
>> 
>> если делать прямо из консоли
>> grep -i "antlr" build.gradle 
>> то получается
>> line 1:5 token recognition error at: '-'
>> Too many positional arguments provided. Provided 3, expected no more than 2
>> line 1:5 token recognition error at: '-'
>> 
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub <https://github.com/e5l/SoftwareDesignAU/pull/2#pullrequestreview-1460911>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AEF18zXEy2S4jPEq82TG4pC2wOdEitxGks5qtuTWgaJpZM4KEST2>.
>> 
>

2016-09-26 06:10 UTC, yurii-litvinov commented
не, нормально, я всё пересобрал с нуля и всё заработало.
но под виндой тест на grep не проходит из-за line ending-ов :)

2016-09-26 06:10 UTC, merged